[package]
name = "space-thumbnails-windows-dll"
version = "1.0.1"
edition = "2021"

[dependencies]
windows = "0.51"
space-thumbnails-windows = { path = "../windows" }
winreg = "0.51"
eventlog = "0.2.2"
log = "0.4"


[lib]
crate-type = ["cdylib"]
